### ISSUE TITLE
Android checklist

### ISSUE THREAD

**Issue by YuChocopie** [chatty-app/chatty-app#34]
- [x]   setting
- [x]   main 헤더

 # 8월 26일까지 목표

## home화면
  *  View
     - [ ] partner 이미지 동그랗게 설정
- [ ] 일기 갯수와 갯수 받아오기
- [ ] 오늘날짜 표시
##  Timeline
  * View
    - [ ]  이미지 둥글게 설정
- [ ]  사용한 이미지 있을 경우 표기
- [ ] 날짜, 요일, 내용 받아오기
## 채팅하기
 *  View
    - [x] 나인패치 적용
    - [x] 전체적인 레이아웃 수정
  - [ ]   작성중인 일기가 있는지 check
  - [ ]   첫 질문 받아오기
  - [ ]   답변을 서버로 보내기 -> 다음 질문 받아오기
  - [ ]   모든 질문에 답을 하지 않았을 때 등의 special case의 경우 처리
  - [ ]   이미지 보내기
## 다이어리 상세보기
* View
    - [x]  item_diary_detail_header 레이아웃 변경
    - [x]  나인패치 적용
- [x]   질문 받아오기
- [x]   유저의 답변 받아오기
- [ ]   날씨 표시
- [ ]   별점 표시
- [ ]   날짜 표시
## Setting
  * View
    - [x]   Link Account
    - [ ]   Friends Setting
    - [x]   Add Question
    - [x]   Notification
    - [x]   Support
- [ ]   Hash 값을 통한 로그인
## Partner Setting
  * View
    - [x]   레이아웃 변경
- [ ]   파트너 추가
- [x]   이미지 변경
- [x]   이름 변경
- [ ]   해당 파트너와 작성한 다이어리 개수와 함깨한 날짜, 시작날짜 받기

# 8월 26일 이후

## 하루의 기분 표시
  * View
    - [ ]   이모지 사용해 레이아웃 제작
- [ ]   날씨 받아오기
- [ ]   하루에 한 개
  * 수정(put)
## 달력
  - [ ]   작성된 날짜 표시
  - [ ]   'month' 별로 선택하는 기능
